name: platform

services:
  core :
    volumes:
      - ./core_container/platform_core:/var/www/core

  app:
    environment:
      - VITE_PLATFORM_URL=${SERVER_IP}:${PUBLISHER_CORE_PORT}/core
      - VITE_SEGURIDAD_URL=${SERVER_IP}:${PUBLISHER_SECURITY_PORT}
    ports:
      - "${APP_PORT:-9636}:9636"
    volumes:
      - ./app_container/platform_app:/app

  publisher:
    ports:
      - "${PUBLISHER_CORE_PORT:-9090}:80"
      # - "${PUBLISHER_APP_PORT:-5190}:8080"
