name: platform

services:
  core :
    environment:
      - LOG_LEVEL=error
      - APP_DEBUG=false
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    restart: always

  app:
    environment:
      - APP_DEBUG=false
      - VITE_PLATFORM_URL=${SERVER_IP}:${PUBLISHER_CORE_PORT}/core
      - VITE_SEGURIDAD_URL=${SERVER_IP}:${PUBLISHER_SECURITY_PORT}
    volumes:
      - ./app_container/platform_app:/app:cached

  publisher:
    ports:
      - "${PUBLISHER_CORE_PORT:-9090}:80"
      - "${PUBLISHER_APP_PORT:-5195}:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    restart: always
        