name: platform

services:
  core :
    environment:
      - APP_DEBUG=true

  app:
    environment:
      - CHOKIDAR_USEPOLLING=1
      - APP_DEBUG=true
      - VITE_PLATFORM_URL=172.16.0.132:9090/core
      - VITE_SEGURIDAD_URL=172.16.0.132:9000
    ports:
      - 9636:9636
    volumes:
      - ./app_container/platform_app:/app

  publisher:
    ports:
      - "9090:80"
      - "5190:8080"
        